-- Roles
INSERT INTO op3dcloud.roles (name) VALUES
  ('admin'),
  ('planner'),
  ('client');

-- Users (auth.users)
INSERT INTO auth.users (
  instance_id,
  id,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  aud,
  role,
  confirmation_token,
  recovery_token,
  email_change_token_new,
  email_change,
  email_change_token_current,
  reauthentication_token,
  phone_change,
  phone_change_token,
  created_at,
  updated_at
) VALUES
  (
    '00000000-0000-0000-0000-000000000000',
    '9cb14807-5fd6-4570-9b6c-f996606d4c11',
    'hernan.arica96@gmail.com',
    crypt('asdf1234', gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}',
    '{
      "sub": "9cb14807-5fd6-4570-9b6c-f996606d4c11",
      "logo": "",
      "name": "hernan",
      "email": "hernan.arica96@gmail.com",
      "notes": "",
      "phone": "+541139361854",
      "entity": "demo",
      "status": "Active",
      "country": "Argentina",
      "credits": 0,
      "planner": "",
      "last_name": "arica",
      "user_type": "Clínica",
      "case_status": "",
      "status_files": "",
      "work_modality": "Caso individual",
      "email_verified": true,
      "phone_verified": false,
      "has_seen_welcome": true,
      "reports_language": "Inglés",
      "treatment_approach": "Estético + Funcional",
      "how_did_you_meet_us": "Redes",
      "digital_model_zocalo_height": "Media",
      "experience_in_digital_planning": "Intermedio"
    }',
    'authenticated',
    'authenticated',
    '', '', '', '', '', '', '', '',
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000002',
    'planner@test.com',
    crypt('asdf1234', gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}',
    '{"sub":"00000000-0000-0000-0000-000000000002","name":"Carlos","last_name":"Planificador","has_seen_welcome":true}',
    'authenticated',
    'authenticated',
    '', '', '', '', '', '', '', '',
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000000',
    '00000000-0000-0000-0000-000000000003',
    'cliente@test.com',
    crypt('asdf1234', gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}',
    '{"sub":"00000000-0000-0000-0000-000000000003","name":"Laura","last_name":"Cliente","has_seen_welcome":true}',
    'authenticated',
    'authenticated',
    '', '', '', '', '', '', '', '',
    now(),
    now()
  );

-- Auth identities (requerido para login por email/password)
INSERT INTO auth.identities (
  id,
  user_id,
  provider_id,
  identity_data,
  provider,
  last_sign_in_at,
  created_at,
  updated_at
) VALUES
  (
    '9cb14807-5fd6-4570-9b6c-f996606d4c11',
    '9cb14807-5fd6-4570-9b6c-f996606d4c11',
    'hernan.arica96@gmail.com',
    '{"sub":"9cb14807-5fd6-4570-9b6c-f996606d4c11","email":"hernan.arica96@gmail.com","email_verified":true}',
    'email',
    now(),
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000002',
    '00000000-0000-0000-0000-000000000002',
    'planner@test.com',
    '{"sub":"00000000-0000-0000-0000-000000000002","email":"planner@test.com","email_verified":true}',
    'email',
    now(),
    now(),
    now()
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    '00000000-0000-0000-0000-000000000003',
    'cliente@test.com',
    '{"sub":"00000000-0000-0000-0000-000000000003","email":"cliente@test.com","email_verified":true}',
    'email',
    now(),
    now(),
    now()
  );

-- Roles de usuarios
INSERT INTO op3dcloud.user_has_role (id_user, id_role) VALUES
  (
    '9cb14807-5fd6-4570-9b6c-f996606d4c11',
    (SELECT id FROM op3dcloud.roles WHERE name = 'admin')
  ),
  (
    '00000000-0000-0000-0000-000000000002',
    (SELECT id FROM op3dcloud.roles WHERE name = 'planner')
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    (SELECT id FROM op3dcloud.roles WHERE name = 'client')
  );

-- Patients (asignados al cliente)
INSERT INTO op3dcloud.patients (
  id_client,
  name,
  last_name,
  type_of_plan,
  treatment_approach,
  treatment_objective,
  dental_restrictions,
  declared_limitations,
  planning_enabled,
  suggested_adminations_and_actions,
  observations_or_instructions,
  sworn_declaration,
  expiration,
  id_planner,
  status_files,
  case_status,
  notes,
  observations,
  status,
  photos,
  xrays,
  scans,
  supplementary_docs
) VALUES
  (
    '00000000-0000-0000-0000-000000000003',
    'Martina',
    'González',
    'Ortodoncia fija',
    'Brackets metálicos con arco de nivelación progresivo',
    ARRAY['Corrección de apiñamiento', 'Mejora de oclusión clase II', 'Cierre de espacios'],
    ARRAY['No extracciones', 'Evitar fuerzas intrusivas en sector anterior'],
    ARRAY['Hipersensibilidad dental', 'Bruxismo nocturno moderado'],
    true,
    ARRAY['Instalar brackets superiores e inferiores', 'Tomar fotografías intraorales iniciales', 'Indicar uso de cera ortodóntica'],
    'Paciente colaboradora. Iniciar con arco 014 NiTi. Control mensual.',
    true,
    '2026-11-15',
    '00000000-0000-0000-0000-000000000002',
    ARRAY['Pendiente'],
    ARRAY['En tratamiento'],
    'Paciente muy motivada. Excelente higiene oral.',
    'Caso de complejidad media. Posible necesidad de elásticos intermaxilares en fase 2.',
    'Active',
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[]
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    'Sebastián',
    'Morales',
    'Ortodoncia invisible',
    'Alineadores secuenciales con uso mínimo de 22 horas diarias',
    ARRAY['Alineación dental superior', 'Corrección de mordida abierta anterior', 'Mejora estética'],
    ARRAY['No usar brackets metálicos', 'Sin expansión palatina'],
    ARRAY['Reflujo gastroesofágico leve', 'Alergia al níquel'],
    true,
    ARRAY['Tomar escaneo intraoral 3D', 'Diseñar plan de alineadores', 'Explicar protocolo de uso y cuidado'],
    'Paciente adulto con altas expectativas estéticas. Revisar compliance en cada control.',
    true,
    '2026-08-30',
    '00000000-0000-0000-0000-000000000002',
    ARRAY['Completo'],
    ARRAY['En planificación'],
    'Viaja frecuentemente. Acordar controles con flexibilidad.',
    'Requiere retención fija inferior al finalizar tratamiento.',
    'Active',
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[]
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    'Valentina',
    'Rojas',
    'Ortodoncia funcional',
    'Aparato funcional miofuncional combinado con ortodoncia fija en fase 2',
    ARRAY['Corrección de clase III esqueletal', 'Estimulación del crecimiento maxilar', 'Mejora de perfil facial'],
    ARRAY['No extracciones en esta fase', 'Evitar carga en molares temporales'],
    ARRAY['Amígdalas hipertróficas', 'Respiración bucal'],
    false,
    ARRAY['Derivar a otorrinolaringólogo', 'Solicitar telerradiografía lateral', 'Realizar análisis cefalométrico'],
    'Paciente en crecimiento activo (10 años). Coordinación interdisciplinaria requerida.',
    true,
    null,
    null,
    ARRAY['Pendiente'],
    ARRAY['Evaluación inicial'],
    'Derivada por pediatra. Primera consulta ortodóncica.',
    'Caso complejo por componente esqueletal. Reevaluar en 6 meses.',
    'Active',
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[]
  ),
  (
    '00000000-0000-0000-0000-000000000003',
    'Diego',
    'Fernández',
    'Retención',
    'Retenedor fijo inferior y placas removibles superiores nocturnas',
    ARRAY['Mantener resultados post-tratamiento', 'Prevenir recidiva de rotaciones'],
    ARRAY['Ninguna'],
    ARRAY['Ninguna declarada'],
    false,
    ARRAY['Cementar retenedor 3-3 inferior', 'Entregar placas removibles superiores', 'Instruir en higiene del retenedor'],
    'Paciente finalizó tratamiento activo. Control semestral. Excelentes resultados.',
    true,
    '2028-03-01',
    '00000000-0000-0000-0000-000000000002',
    ARRAY['Completo'],
    ARRAY['Finalizado'],
    'Tratamiento completado exitosamente en 18 meses.',
    'Resultados estables. Continuar con retención indefinida.',
    'Inactive',
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[],
    ARRAY[]::text[]
  );

-- Treatment planning (solo para pacientes con planning_enabled = true)
INSERT INTO op3dcloud.treatment_planning (
  patient_id,
  video_url,
  technical_report_url,
  upper_aligners,
  lower_aligners,
  complexity,
  prognosis,
  diagnosis,
  laboratory,
  planning,
  restrictions,
  tracking_rotations,
  tracking_extrusions,
  tracking_extrusion_buttons,
  tracking_intrusions,
  tracking_torque,
  tracking_angulations,
  tracking_translations,
  tracking_expansion,
  commercial_potential,
  quality_information,
  quality_scan,
  quality_xrays,
  quality_intraoral,
  quality_extraoral,
  additional_observations
) VALUES
  (
    (SELECT id FROM op3dcloud.patients WHERE name = 'Martina' AND last_name = 'González'),
    null,
    null,
    0,
    0,
    'Alta',
    'Favorable',
    ARRAY['Apiñamiento severo sector anterior superior e inferior', 'Clase II división 1', 'Overjet aumentado (5mm)', 'Curva de Spee acentuada'],
    ARRAY['Brackets slot 0.022 prescripción MBT', 'Arcos NiTi redondos fase inicial', 'Arcos rectangulares de acero fase de detallado', 'Cadenas elásticas sector anterior superior'],
    ARRAY['Alineación y nivelación en 3 fases progresivas', 'Retracción anterior con mecánica de deslizamiento', 'Uso de elásticos intermaxilares clase II en fase 2', 'Detallado y finishing con arcos 019x025 SS'],
    ARRAY['No intrusión de incisivos superiores por riesgo periodontal', 'Preservar anclaje posterior - evitar mesialización de molares'],
    '13, 23, 33, 43',
    null,
    null,
    null,
    '11, 21',
    null,
    null,
    null,
    ARRAY['Blanqueamiento dental post-tratamiento', 'Carillas en incisivos superiores para mejora estética final'],
    ARRAY['Información completa y bien documentada'],
    ARRAY['Escaneo de buena calidad'],
    ARRAY['Radiografía panorámica con buena definición', 'Telerradiografía lateral incluida'],
    ARRAY['Fotos intraorales con buena iluminación'],
    ARRAY['Fotos de perfil y frontal correctas'],
    'Caso de alta complejidad con excelente motivación de la paciente. Se espera duración de 18 a 22 meses. Controles mensuales obligatorios.'
  ),
  (
    (SELECT id FROM op3dcloud.patients WHERE name = 'Sebastián' AND last_name = 'Morales'),
    null,
    null,
    24,
    20,
    'Baja',
    'Favorable',
    ARRAY['Apiñamiento leve sector anterior superior', 'Mordida abierta anterior (2mm)', 'Espaciamiento inferior resuelto previamente'],
    ARRAY['Attachments rectangulares en caninos y premolares superiores', 'Botones de extrusión en 11 y 21', 'Elásticos verticales anteriores para cierre de mordida'],
    ARRAY['Expansión transversal superior leve en primeras 8 semanas', 'Intrusión de sectores posteriores para corrección de mordida abierta', 'Proclinación controlada de incisivos superiores', 'Retención fija 3-3 inferior al finalizar'],
    ARRAY['No usar ningún componente metálico - alergia al níquel confirmada', 'Solo alineadores, sin brackets de emergencia'],
    '13, 23',
    '11, 21',
    '11, 21',
    null,
    null,
    null,
    null,
    '16, 26, 36, 46',
    ARRAY['Retenedor de Hawley superior complementario nocturno', 'Control de ATM al finalizar tratamiento'],
    ARRAY['Información completa'],
    ARRAY['Escaneo intraoral 3D de excelente calidad'],
    ARRAY['Panorámica actualizada'],
    ARRAY['Serie fotográfica intraoral completa'],
    ARRAY['Fotos extraorales con buena calidad'],
    'Paciente con alta motivación estética y comprensión del protocolo. Compliance esperado alto. Revisar uso de alineadores en cada control - mínimo 22hs/día.'
  );
